#!/usr/bin/env bash
# Assemble the iOS extraction bundle from the browser extension's sources.
#
# Tome has exactly one extraction implementation, and this script is what keeps
# it that way. The extension injects lib/Readability.js + extractors/*.js as
# separate files and dispatches with runExtractors(); iOS can't do that, because
# NSExtensionJavaScriptPreprocessingFile takes exactly ONE file. So we
# concatenate the same sources, in the same order, into one bundle.
#
# runExtractors() is lifted out of background.js between marker comments rather
# than copied, so the app and the extension can never drift apart on which
# extractor wins a page.
#
# Runs from Xcode as a build phase (SRCROOT is set) and standalone from a shell.
# Safe to re-run; output is derived and gitignored.

set -euo pipefail

# ------------------------------------------------------------------- paths --
# From Xcode, SRCROOT is ios/. Standalone, derive it from this script's path.
if [ -n "${SRCROOT:-}" ]; then
    IOS_DIR="$SRCROOT"
else
    IOS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
REPO_ROOT="$(cd "$IOS_DIR/.." && pwd)"

EXT_DIR="$REPO_ROOT/extension"
OUT_DIR="$IOS_DIR/Resources/Generated"
OUT_JS="$OUT_DIR/TomeExtraction.js"
OUT_CSS="$OUT_DIR/reader.css"

BACKGROUND_JS="$EXT_DIR/background.js"
GLUE_JS="$IOS_DIR/Scripts/tome-ios-glue.js"

# Order matters and mirrors EXTRACTOR_FILES in background.js: the library first,
# then extractors in any order (priority decides who actually runs).
SOURCES=(
    "$EXT_DIR/lib/Readability.js"
    "$EXT_DIR/extractors/x.js"
    "$EXT_DIR/extractors/generic.js"
)

die() { echo "error: $*" >&2; exit 1; }

for f in "${SOURCES[@]}" "$BACKGROUND_JS" "$GLUE_JS" "$EXT_DIR/reader.css"; do
    [ -f "$f" ] || die "missing source: $f"
done

mkdir -p "$OUT_DIR"

# ------------------------------------------------------------- concatenate --
# Needs a .js suffix: `node --check` infers module format from the extension and
# refuses a bare mktemp name.
tmpdir="$(mktemp -d)"
tmp="$tmpdir/TomeExtraction.js"
trap 'rm -rf "$tmpdir"' EXIT

{
    echo "/* GENERATED by ios/Scripts/build-extraction-js.sh — do not edit."
    echo " * Sources: extension/lib/Readability.js, extension/extractors/*.js,"
    echo " * runExtractors() from extension/background.js, ios/Scripts/tome-ios-glue.js"
    echo " */"
    echo

    for f in "${SOURCES[@]}"; do
        echo "/* ===== ${f#"$REPO_ROOT"/} ===== */"
        cat "$f"
        # Sources are IIFEs or function declarations, but a file whose last line
        # lacks a newline would otherwise weld itself onto the next banner.
        echo
        echo
    done

    echo "/* ===== runExtractors() from extension/background.js ===== */"
    # sed prints the span between the markers, exclusive of the markers.
    dispatch="$(sed -n '/#tome:dispatch-start/,/#tome:dispatch-end/p' "$BACKGROUND_JS" \
        | sed '1d;$d')"
    [ -n "$dispatch" ] || die "dispatch markers not found in background.js — \
did the #tome:dispatch-start / #tome:dispatch-end comments get removed?"
    echo "$dispatch"
    echo

    echo "/* ===== ios/Scripts/tome-ios-glue.js ===== */"
    cat "$GLUE_JS"
} > "$tmp"

# ---------------------------------------------------------------- validate --
# Catches a botched concatenation (an unbalanced brace welding two files
# together) here, at build time, instead of as a silent no-op inside Apple's JS
# preprocessing sandbox where there is nowhere for the error to surface.
if command -v node >/dev/null 2>&1; then
    node --check "$tmp" || die "generated bundle is not valid JavaScript"
else
    echo "warning: node not found — skipping syntax check of the bundle" >&2
fi

# Every extractor must survive into the bundle; a silently-dropped one would
# just look like "the X extractor stopped working" months later.
for needle in "function Readability" "x-article" "generic-readability" \
              "function runExtractors" "ExtensionPreprocessingJS"; do
    grep -q "$needle" "$tmp" || die "bundle is missing '$needle'"
done

# --------------------------------------------------------------- install ---
# Only touch the outputs when they actually change, so Xcode doesn't treat every
# build as dirty.
if ! cmp -s "$tmp" "$OUT_JS"; then
    cp "$tmp" "$OUT_JS"
    echo "wrote $OUT_JS ($(wc -l < "$OUT_JS" | tr -d ' ') lines)"
else
    echo "$OUT_JS already current"
fi

# reader.css ships alongside so the app can put it in the payload, exactly as
# the extension does (background.js readerCSS -> pdfgen.go buildHTML). Without
# it the server falls back to its own compact approximation and the PDF quietly
# stops matching the desktop output.
if ! cmp -s "$EXT_DIR/reader.css" "$OUT_CSS"; then
    cp "$EXT_DIR/reader.css" "$OUT_CSS"
    echo "wrote $OUT_CSS"
else
    echo "$OUT_CSS already current"
fi
